import 'package:flutter/material.dart';

const Map<String, String> _intlCategoryNames = {
  'food': 'Dining',
  'transport': 'Transport',
  'shopping': 'Shopping',
  'entertainment': 'Entertainment',
  'housing': 'Living',
  'health': 'Healthcare',
  'education': 'Education',
  'beauty': 'Beauty',
  'social': 'Social',
  'travel': 'Travel',
  'sports': 'Sports',
  'coffee': 'Coffee',
  'snack': 'Snacks',
  'fruit': 'Fruit',
  'daily': 'Daily',
  'other': 'Other',
  'grocery': 'Groceries',
  'takeout': 'Takeout',
  'vegetable': 'Vegetables',
  'drink': 'Drinks',
  'clothing': 'Clothing',
  'phone': 'Phone Bill',
  'rent': 'Rent',
  'mortgage': 'Mortgage',
  'housing2': 'Housing',
  'gift_exp': 'Gifts',
  'tobacco': 'Tobacco & Alcohol',
  'express': 'Delivery',
  'fandom': 'Fandom',
  'game': 'Gaming',
  'digital': 'Digital',
  'movie': 'Movie Tickets',
  'car': 'Car',
  'motorcycle': 'Motorcycle',
  'gas': 'Fuel',
  'book': 'Books',
  'study': 'Study',
  'pet': 'Pets',
  'water': 'Water Bill',
  'electric': 'Electricity',
  'gas_fee': 'Gas Bill',
  'childcare': 'Childcare',
  'elder': 'Family',
  'lease': 'Lease',
  'office': 'Office',
  'repair': 'Repairs',
  'lottery': 'Lottery',
  'donation': 'Donations',
  'mahjong': 'Mahjong',
  'salary': 'Salary',
  'bonus': 'Bonus',
  'investment': 'Investment Income',
  'gift': 'Gift',
  'refund': 'Refund',
  'other_income': 'Other',
  'cash_gift': 'Cash Gift',
  'lend': 'Lent Out',
  'repay': 'Repayment',
  'transfer_in': 'Transfer',
};

String localizedCategoryName({
  required String id,
  required String fallback,
  required Locale locale,
}) {
  if (locale.languageCode == 'zh') return fallback;
  return _intlCategoryNames[id] ?? fallback;
}
